=== Absenior03/AnnapurnaTours/atat/web_lab4/tourismAgency.dtd
<!ELEMENT tourismAgency (agency+)>
<!ELEMENT agency (name, location, yearEstablished, totalPackages, currency, rating)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT yearEstablished (#PCDATA)>
<!ELEMENT totalPackages (#PCDATA)>
<!ELEMENT currency (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

=== Absenior03/AnnapurnaTours/atat/web_lab4/tourismAgency.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tourismAgency SYSTEM "tourismAgency.dtd">
<tourismAgency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="tourismAgency.xsd">
    <agency>
        <name>Global Travels</name>
        <location>New York</location>
        <yearEstablished>1995</yearEstablished>
        <totalPackages>120</totalPackages>
        <currency>USD</currency>
        <rating>4.5</rating>
    </agency>
    <agency>
        <name>Sunny Tours</name>
        <location>Sydney</location>
        <yearEstablished>2002</yearEstablished>
        <totalPackages>85</totalPackages>
        <currency>AUD</currency>
        <rating>4.7</rating>
    </agency>
    <agency>
        <name>Explorer's Delight</name>
        <location>London</location>
        <yearEstablished>1988</yearEstablished>
        <totalPackages>150</totalPackages>
        <currency>GBP</currency>
        <rating>4.9</rating>
    </agency>
</tourismAgency>
